### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trigger' of undefined

### ISSUE THREAD

**Issue by pearson-lucas-dev** [richie5um/focus-mode#2]
[Enter steps to reproduce below:]

1) Installed focus-mode
2) Pressed ctrl-alt-z
3) Big red thing in top right corner!

**Atom Version**: 1.0.2
**System**: Linux Mint
**Thrown From**: [focus-mode](https://github.com/richie5um/focus-mode) package, v0.4.0
### Stack Trace

Uncaught TypeError: Cannot read property 'trigger' of undefined

```
At /home/developer/.atom/packages/focus-mode/lib/focus-mode.coffee:36

TypeError: Cannot read property 'trigger' of undefined
  at Object.module.exports.FocusMode.toggle (/home/developer/.atom/packages/focus-mode/lib/focus-mode.coffee:36:25)
  at atom-workspace.subscriptions.add.atom.commands.add.focus-mode:toggle (/home/developer/.atom/packages/focus-mode/lib/focus-mode.coffee:16:85)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:520:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:355:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:177:20)

```
### Commands

```
     -6:08.3.0 project-find:show (atom-text-editor.editor.is-focused)
     -6:06.5.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -6:05.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -5:03.1.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -3:58.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -1:27.6.0 settings-view:open (input#core.autoHideMenuBar.)
  5x -1:21.5.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -1:15.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:21.9.0 focus-mode:toggle (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui.find-visible)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
autocomplete-php, v0.3.6
focus-mode, v0.4.0

# Dev
No dev packages
```

**Comment by richie5um** [comment]
I've stopped using Atom, but I'll take a look at the code to see what needs fixing.

**Comment by ubani** [comment]
Any news on this? What are you using now? 
I've switched from Sublime Text.

**Comment by pearson-lucas-dev** [comment]
@ubani I use atom I just keep things tidy up myself. I am on version 1.3.1 and it seems to be better with each update. Never used Sublime Text but I have only ever heard good things.  I think it is all preference at this point.  Use the tool for the job.
